"""
make relevant import_record fields nullable

Revision ID: 01594f25174d
Revises: d880ad8bd2ef
Create Date: 2025-03-25 05:07:59.411614+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '01594f25174d'
down_revision: Union[str, None] = 'd880ad8bd2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_result', 'failure_details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('import_result', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_result', 'failure_details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import_result', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
