"""
add enhancement supersession root index

Revision ID: 068f01d7c1f8
Revises: 4ce1b7909690
Create Date: 2026-10-05 20:32:25.496634+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '068f01d7c1f8'
down_revision: Union[str, None] = '4ce1b7909690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '3s'")
    op.create_index('ix_enhancement_successor_root_id_id', 'enhancement', ['root_id', 'id'], unique=False, postgresql_where=sa.text('supersedes IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '3s'")
    op.drop_index('ix_enhancement_successor_root_id_id', table_name='enhancement', postgresql_where=sa.text('supersedes IS NOT NULL'))
    # ### end Alembic commands ###
