"""
add reference_duplicate_decision duplicate_determination index

Revision ID: 09660e11fac0
Revises: 6c3d59783d91
Create Date: 2025-09-24 07:52:55.127188+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '09660e11fac0'
down_revision: Union[str, None] = '6c3d59783d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reference_duplicate_decision_duplicate_determination', 'reference_duplicate_decision', ['duplicate_determination'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_duplicate_decision_duplicate_determination', table_name='reference_duplicate_decision')
    # ### end Alembic commands ###
