"""
remove unique constraint on enhancements

Revision ID: 148b5e9b8c30
Revises: 8cb47e5cfb56
Create Date: 2025-06-02 23:28:14.646721+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '148b5e9b8c30'
down_revision: Union[str, None] = '8cb47e5cfb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_enhancement'), 'enhancement', type_='unique')
    op.drop_column('enhancement', 'content_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancement', sa.Column('content_version', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uix_enhancement'), 'enhancement', ['enhancement_type', 'reference_id', 'source'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
