"""
add canonical_reference_id index to duplicate_decision table

Revision ID: 15a866774b9e
Revises: 1a717e152dff
Create Date: 2025-11-25 02:09:16.297125+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '15a866774b9e'
down_revision: Union[str, None] = '1a717e152dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reference_duplicate_decision_active_canonical_reference_id', 'reference_duplicate_decision', ['canonical_reference_id', 'active_decision'], unique=False, postgresql_where=sa.text('active_decision IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_duplicate_decision_active_canonical_reference_id', table_name='reference_duplicate_decision', postgresql_where=sa.text('active_decision IS true'))
    # ### end Alembic commands ###
