"""
add source to pending_enhancement and make enhancement_request_id optional

Revision ID: 1d8078bc0a95
Revises: e8133082064b
Create Date: 2025-10-22 01:00:38.019356+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1d8078bc0a95'
down_revision: Union[str, None] = 'e8133082064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_enhancement', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('pending_enhancement', 'enhancement_request_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_enhancement', 'enhancement_request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pending_enhancement', 'source')
    # ### end Alembic commands ###
