"""
removed callback url from import_batch

Revision ID: 23be8d595cc0
Revises: bcab56693224
Create Date: 2025-09-10 05:31:29.108962+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '23be8d595cc0'
down_revision: Union[str, None] = 'bcab56693224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'callback_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batch', sa.Column('callback_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
