"""
Add entitlements to robot

Revision ID: 26e037f4b54f
Revises: 88264d67fc82
Create Date: 2026-05-14 01:05:08.034601+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26e037f4b54f'
down_revision: Union[str, None] = '88264d67fc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('entitlements', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'entitlements')
    # ### end Alembic commands ###
