"""
relax identifier unique index

Revision ID: 276b5f9de690
Revises: 6a12f6e0150f
Create Date: 2025-08-20 04:59:33.677437+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '276b5f9de690'
down_revision: Union[str, None] = '6a12f6e0150f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_external_identifier'), 'external_identifier', type_='unique')
    op.create_unique_constraint('uix_external_identifier', 'external_identifier', ['identifier_type', 'identifier', 'other_identifier_name', 'reference_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_external_identifier', 'external_identifier', type_='unique')
    op.create_unique_constraint(op.f('uix_external_identifier'), 'external_identifier', ['identifier_type', 'identifier', 'other_identifier_name'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
