"""
add linked_data_concept_filters to search_export

Revision ID: 28b7dc9e4013
Revises: 26e037f4b54f
Create Date: 2026-05-26 05:21:37.071215+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b7dc9e4013'
down_revision: Union[str, None] = '26e037f4b54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_export', sa.Column('linked_data_concept_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_export', 'linked_data_concept_filters')
    # ### end Alembic commands ###
