"""
add discarded to pending enhancement status

Revision ID: 30643f185bd2
Revises: 1d8078bc0a95
Create Date: 2025-11-03 23:03:50.512439+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '30643f185bd2'
down_revision: Union[str, None] = '1d8078bc0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE pendingenhancementstatus ADD VALUE IF NOT EXISTS 'DISCARDED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
