"""
Add enhancement requests table

Revision ID: 32f03920c8b1
Revises: e55630485612
Create Date: 2025-04-23 03:46:01.605208+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f03920c8b1'
down_revision: Union[str, None] = 'e55630485612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhancementrequest',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('enhancement_type', postgresql.ENUM('bibliographic', 'abstract', 'annotation', 'location', 'full text', name='enhancement_type'), nullable=False),
    sa.Column('request_status', postgresql.ENUM('received', 'accepted', 'rejected', 'failed', 'completed', name='request_status'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enhancementrequest')
    # ### end Alembic commands ###
