"""
remove enhancement request table

Revision ID: 3418c332afa8
Revises: 6a12f6e0150f
Create Date: 2025-08-25 22:10:15.785776+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3418c332afa8'
down_revision: Union[str, None] = '6a12f6e0150f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enhancement_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhancement_request',
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('robot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_status', postgresql.ENUM('received', 'accepted', 'rejected', 'failed', 'completed', name='request_status'), autoincrement=False, nullable=False),
    sa.Column('enhancement_parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], name=op.f('enhancement_request_reference_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enhancement_request_pkey'))
    )
    # ### end Alembic commands ###
