"""
add duplicate mapping to reference

Revision ID: 3e4d86a652e0
Revises: 276b5f9de690
Create Date: 2025-08-21 03:10:31.460164+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3e4d86a652e0'
down_revision: Union[str, None] = '276b5f9de690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('duplicate_of', sa.UUID(), nullable=True))
    op.create_index('ix_reference_duplicate_of', 'reference', ['duplicate_of'], unique=False)
    op.create_foreign_key(None, 'reference', 'reference', ['duplicate_of'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_index('ix_reference_duplicate_of', table_name='reference')
    op.drop_column('reference', 'duplicate_of')
    # ### end Alembic commands ###
