"""
add duplicate mapping to reference

Revision ID: 3e4d86a652e0
Revises: 276b5f9de690
Create Date: 2025-08-21 03:10:31.460164+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3e4d86a652e0'
down_revision: Union[str, None] = '276b5f9de690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """REMOVED - deprecated"""
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """REMOVED - deprecated"""
    # ### end Alembic commands ###
