"""
add enhancement supersedes unique index

Revision ID: 4ce1b7909690
Revises: 69c1a291fb0a
Create Date: 2026-10-05 03:25:20.873886+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ce1b7909690'
down_revision: Union[str, None] = '69c1a291fb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '3s'")
    op.create_index('uq_enhancement_supersedes', 'enhancement', ['supersedes'], unique=True, postgresql_where=sa.text('supersedes IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '3s'")
    op.drop_index('uq_enhancement_supersedes', table_name='enhancement', postgresql_where=sa.text('supersedes IS NOT NULL'))
    # ### end Alembic commands ###
