"""
add country and region filters to search_export

Revision ID: 54bf97d7f368
Revises: 28b7dc9e4013
Create Date: 2026-05-28 03:56:59.986564+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54bf97d7f368'
down_revision: Union[str, None] = '28b7dc9e4013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_export', sa.Column('linked_data_country_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_export', sa.Column('linked_data_country_wb_region_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_export', 'linked_data_country_wb_region_filters')
    op.drop_column('search_export', 'linked_data_country_filters')
    # ### end Alembic commands ###
