"""
Add robot_enhancement_batch and pending_enhancement tables

Revision ID: 5f5b2e791c6e
Revises: 8fc1a39aad48
Create Date: 2025-08-28 05:14:48.260955+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5f5b2e791c6e'
down_revision: Union[str, None] = '8fc1a39aad48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pending_enhancement_status_enum = sa.Enum(
    "PENDING", "ACCEPTED", "IMPORTING", "INDEXING", "INDEXING_FAILED", "COMPLETED", "FAILED", name="pendingenhancementstatus"
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_enhancement_batch',
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('reference_data_file', sa.String(), nullable=True),
    sa.Column('result_file', sa.String(), nullable=True),
    sa.Column('validation_result_file', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_enhancement',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('enhancement_request_id', sa.UUID(), nullable=False),
    sa.Column('robot_enhancement_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', pending_enhancement_status_enum, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enhancement_request_id'], ['enhancement_request.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.ForeignKeyConstraint(['robot_enhancement_batch_id'], ['robot_enhancement_batch.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_enhancement')
    op.drop_table('robot_enhancement_batch')
    op.execute('DROP TYPE pendingenhancementstatus')
    # ### end Alembic commands ###
