"""
add failed_retryable to import_batch_status

Revision ID: 64242843905a
Revises: 76102fddd9c6
Create Date: 2025-06-18 23:58:57.284338+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64242843905a'
down_revision: Union[str, None] = 'da69ac761676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE import_batch_status ADD VALUE IF NOT EXISTS 'retrying'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
