"""
add more unique constraints and cascades

Revision ID: 65eb6abe0dc7
Revises: bd0909fe08fb
Create Date: 2025-04-08 06:21:00.449642+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65eb6abe0dc7'
down_revision: Union[str, None] = 'bd0909fe08fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE collision_strategy AS ENUM ('discard', 'fail', 'overwrite', 'merge_aggressive', 'merge_defensive')")
    op.create_unique_constraint('uix_enhancement', 'enhancement', ['enhancement_type', 'reference_id', 'source', 'content'])
    op.add_column('import_batch', sa.Column('collision_strategy', postgresql.ENUM('discard', 'fail', 'overwrite', 'merge_aggressive', 'merge_defensive', name='collision_strategy'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'collision_strategy')
    op.drop_constraint('uix_enhancement', 'enhancement', type_='unique')
    op.execute("DROP TYPE collision_strategy")
    # ### end Alembic commands ###
