"""
add indexing enums to batch enhancement requests

Revision ID: 6a12f6e0150f
Revises: 83ad32cea879
Create Date: 2025-06-27 02:30:55.090872+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6a12f6e0150f'
down_revision: Union[str, None] = '83ad32cea879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE batch_enhancement_request_status ADD VALUE IF NOT EXISTS 'indexing'")
    op.execute("ALTER TYPE batch_enhancement_request_status ADD VALUE IF NOT EXISTS 'indexing_failed'")

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
