"""
remove collision_strategy

Revision ID: 6f6d08aab362
Revises: e2b5649fcd0b
Create Date: 2025-10-02 23:27:25.113341+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f6d08aab362'
down_revision: Union[str, None] = 'e2b5649fcd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'collision_strategy')
    op.execute('DROP TYPE collision_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batch', sa.Column('collision_strategy', postgresql.ENUM('discard', 'fail', 'overwrite', 'merge_aggressive', 'merge_defensive', name='collision_strategy'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
