"""
remove request_status enum

Revision ID: 7042fe692130
Revises: c4b31f92a4a1
Create Date: 2025-08-27 04:26:34.289519+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7042fe692130'
down_revision: Union[str, None] = 'c4b31f92a4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE request_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE request_status AS ENUM('received', 'accepted', 'rejected', 'failed', 'completed')")
    # ### end Alembic commands ###
