"""
add search fields to enhancement request

Revision ID: 73a049948581
Revises: f3a9c7e21b04
Create Date: 2026-07-23 23:53:25.225815+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73a049948581'
down_revision: Union[str, None] = 'f3a9c7e21b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancement_request', sa.Column('search', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enhancement_request', sa.Column('search_status', sa.String(), nullable=True))
    op.add_column('enhancement_request', sa.Column('n_matched', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enhancement_request', 'n_matched')
    op.drop_column('enhancement_request', 'search_status')
    op.drop_column('enhancement_request', 'search')
    # ### end Alembic commands ###
