"""
Add derived_from to enhancement

Revision ID: 76102fddd9c6
Revises: cba2a740897b
Create Date: 2025-06-05 06:56:46.327786+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76102fddd9c6'
down_revision: Union[str, None] = 'cba2a740897b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancement', sa.Column('derived_from', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enhancement', 'derived_from')
    # ### end Alembic commands ###
