"""
Add pending_enhancement and robot_enhancement_batch tables

Revision ID: 77fbe0864996
Revises: 6a12f6e0150f
Create Date: 2025-08-21 06:15:57.211506+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77fbe0864996'
down_revision: Union[str, None] = '6a12f6e0150f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

robot_enhancement_batch_status_enum = sa.Enum(
    "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="robotenhancementbatchstatus"
)
pending_enhancement_status_enum = sa.Enum(
    "PENDING", "PROCESSED", name="pendingenhancementstatus"
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_enhancement_batch',
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('status', robot_enhancement_batch_status_enum, nullable=False),
    sa.Column('reference_file', sa.String(), nullable=True),
    sa.Column('result_file', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_enhancement',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('batch_enhancement_request_id', sa.UUID(), nullable=False),
    sa.Column('robot_enhancement_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', pending_enhancement_status_enum, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_enhancement_request_id'], ['batch_enhancement_request.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.ForeignKeyConstraint(['robot_enhancement_batch_id'], ['robot_enhancement_batch.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_enhancement')
    op.drop_table('robot_enhancement_batch')
    op.execute('DROP TYPE robotenhancementbatchstatus')
    op.execute('DROP TYPE pendingenhancementstatus')
    # ### end Alembic commands ###
