"""
add expiry and retry columns to pending_enhancement

Revision ID: 7afd162b774a
Revises: 1d8078bc0a95
Create Date: 2025-10-24 04:34:16.819322+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7afd162b774a'
down_revision: Union[str, None] = '1d8078bc0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Manipulate enums
    op.execute("ALTER TYPE pendingenhancementstatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    op.execute("ALTER TYPE pendingenhancementstatus ADD VALUE IF NOT EXISTS 'EXPIRED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
