"""
drop pendingenhancementstatus enum

Revision ID: 7afd162b774a
Revises: 30643f185bd2
Create Date: 2025-10-24 04:34:16.819322+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7afd162b774a'
down_revision: Union[str, None] = '30643f185bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_enhancement', 'status', type_=sa.String(), nullable=False)
    op.execute("DROP TYPE IF EXISTS pendingenhancementstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Not safely downgradable. We can create the enum type, but can't
    # apply it to the pending_enhancement table without triggering the problem
    # we're trying to avoid. See also https://github.com/destiny-evidence/destiny-repository/pull/343#discussion_r2458931314
    pass
