"""
add enhance_incoming_references to robot model

Revision ID: 7b61b2ef39fa
Revises: da69ac761676
Create Date: 2025-06-13 06:52:33.143987+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7b61b2ef39fa'
down_revision: Union[str, None] = 'da69ac761676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('enhance_incoming_references', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'enhance_incoming_references')
    # ### end Alembic commands ###
