"""
Remove enhancement request status enum type

Revision ID: 7bb7cd39e022
Revises: 75680bf07a66
Create Date: 2026-01-19 00:47:31.366795+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bb7cd39e022'
down_revision: Union[str, None] = '75680bf07a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enhancement_request', 'request_status', type_=sa.String(), existing_nullable=False)
    op.execute("DROP TYPE IF EXISTS enhancement_request_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Cannot be safely downgraded. We can create the enum type, but can't
    # apply it to the table without triggering the problem
    # we're trying to avoid. See also https://github.com/destiny-evidence/destiny-repository/pull/343#discussion_r2458931314
    pass
