"""
Added enhancement request table

Revision ID: 8122d8e2dc7d
Revises: e55630485612
Create Date: 2025-05-05 04:48:48.479447+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8122d8e2dc7d'
down_revision: Union[str, None] = 'e55630485612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhancement_request',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('request_status', postgresql.ENUM('received', 'accepted', 'rejected', 'failed', 'completed', name='request_status'), nullable=False),
    sa.Column('enhancement_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enhancement_request')
    # ### end Alembic commands ###
