"""
updating import enums

Revision ID: 82d391499bca
Revises: 7042fe692130
Create Date: 2025-09-05 07:20:58.422532+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '82d391499bca'
down_revision: Union[str, None] = '7042fe692130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE import_batch_status ADD VALUE IF NOT EXISTS 'partially_failed'")
    op.execute("ALTER TYPE import_result_status ADD VALUE IF NOT EXISTS 'retrying'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
