"""
add source to enhancement requests

Revision ID: 83ad32cea879
Revises: 339899ffe244
Create Date: 2025-06-25 03:18:31.630573+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '83ad32cea879'
down_revision: Union[str, None] = '339899ffe244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_enhancement_request', sa.Column('source', sa.String(), nullable=True))
    op.add_column('enhancement_request', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enhancement_request', 'source')
    op.drop_column('batch_enhancement_request', 'source')
    # ### end Alembic commands ###
