"""
add search_export table

Revision ID: 88264d67fc82
Revises: 5bdf392a9e6a
Create Date: 2026-05-11 08:19:34.574168+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88264d67fc82'
down_revision: Union[str, None] = '5bdf392a9e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_export',
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('annotation_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('sort', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_file', sa.String(), nullable=True),
    sa.Column('n_references', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_export')
    # ### end Alembic commands ###
