"""
add processed to batch enhancement status

Revision ID: 8cb47e5cfb56
Revises: 00254b0eceb0
Create Date: 2025-05-23 04:08:30.454313+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8cb47e5cfb56'
down_revision: Union[str, None] = '00254b0eceb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE batch_enhancement_request_status ADD VALUE IF NOT EXISTS 'importing'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
