"""
add index to enhancement type

Revision ID: 8e1b2eb0098b
Revises: f8ad6d4b122a
Create Date: 2025-06-23 01:21:01.940515+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8e1b2eb0098b'
down_revision: Union[str, None] = 'f8ad6d4b122a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enhancement_enhancement_type', 'enhancement', ['enhancement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enhancement_enhancement_type', table_name='enhancement')
    # ### end Alembic commands ###
