"""
Add import batch model

Revision ID: 8fb8831fb527
Revises: e3982035daf7
Create Date: 2025-02-12 09:51:59.202962+00:00

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8fb8831fb527"
down_revision: Union[str, None] = "e3982035daf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "importbatch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created", "started", "completed", "cancelled", name="importbatchstatus"
            ),
            nullable=False,
        ),
        sa.Column("storage_url", sqlmodel.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", "import_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("importbatch")
    # ### end Alembic commands ###
