"""
add status to import batch compound index

Revision ID: 8fc1a39aad48
Revises: 23be8d595cc0
Create Date: 2025-09-11 05:24:49.096569+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8fc1a39aad48'
down_revision: Union[str, None] = '23be8d595cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_result_import_batch_id'), table_name='import_result')
    op.create_index('ix_import_result_import_batch_id_status', 'import_result', ['import_batch_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_result_import_batch_id_status', table_name='import_result')
    op.create_index(op.f('ix_import_result_import_batch_id'), 'import_result', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###
