"""
add batch_enhancement_request table

Revision ID: 98b8fa7bc210
Revises: e452ec50ed26
Create Date: 2025-05-20 04:54:44.008632+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98b8fa7bc210'
down_revision: Union[str, None] = 'e452ec50ed26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_enhancement_request',
    sa.Column('reference_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('request_status', postgresql.ENUM('received', 'accepted', 'rejected', 'partial_failed', 'failed', 'completed', name='batch_enhancement_request_status'), nullable=False),
    sa.Column('enhancement_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_enhancement_request')
    # ### end Alembic commands ###
