"""
add callback url

Revision ID: a59a0d4dc6dc
Revises: 65eb6abe0dc7
Create Date: 2025-04-10 03:42:14.129912+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a59a0d4dc6dc'
down_revision: Union[str, None] = '65eb6abe0dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batch', sa.Column('callback_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'callback_url')
    # ### end Alembic commands ###
