"""
add batch_enhancement_request.reference_data_file

Revision ID: b660ebcd83e1
Revises: 98b8fa7bc210
Create Date: 2025-05-21 03:50:16.108831+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b660ebcd83e1'
down_revision: Union[str, None] = '98b8fa7bc210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_enhancement_request', sa.Column('reference_data_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_enhancement_request', 'reference_data_file')
    # ### end Alembic commands ###
