"""
remove status from import_batch table

Revision ID: bcab56693224
Revises: 82d391499bca
Create Date: 2025-09-08 03:19:45.799140+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcab56693224'
down_revision: Union[str, None] = '82d391499bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'status')
    op.execute("DROP TYPE import_batch_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batch', sa.Column('status', postgresql.ENUM('created', 'started', 'completed', 'cancelled', 'failed', 'indexing', 'indexing_failed', 'retrying', 'partially_failed', name='import_batch_status'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
