"""
add export_format to search_export

Revision ID: bce864c7c06e
Revises: 54bf97d7f368
Create Date: 2026-06-29 06:14:55.426584+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bce864c7c06e'
down_revision: Union[str, None] = '54bf97d7f368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_export', sa.Column('export_format', sa.String(), server_default='jsonl', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_export', 'export_format')
    # ### end Alembic commands ###
