"""
add unique constraints

Revision ID: bd0909fe08fb
Revises: d3c0f4b3f6c6
Create Date: 2025-04-04 04:25:01.726595+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bd0909fe08fb'
down_revision: Union[str, None] = 'd3c0f4b3f6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_external_identifier', 'external_identifier', ['identifier_type', 'identifier', 'other_identifier_name'], postgresql_nulls_not_distinct=True)
    op.create_unique_constraint('uix_import_batch', 'import_batch', ['import_record_id', 'storage_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_import_batch', 'import_batch', type_='unique')
    op.drop_constraint('uix_external_identifier', 'external_identifier', type_='unique')
    # ### end Alembic commands ###
