"""
add indexing to import_batch_status

Revision ID: da69ac761676
Revises: cba2a740897b
Create Date: 2025-06-10 05:24:54.060127+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'da69ac761676'
down_revision: Union[str, None] = '76102fddd9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE import_batch_status ADD VALUE IF NOT EXISTS 'indexing'")
    op.execute("ALTER TYPE import_batch_status ADD VALUE IF NOT EXISTS 'indexing_failed'")
    op.execute("ALTER TYPE batch_enhancement_request_status ADD VALUE IF NOT EXISTS 'indexing'")
    op.execute("ALTER TYPE batch_enhancement_request_status ADD VALUE IF NOT EXISTS 'indexing_failed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
