"""
add import models

Revision ID: de20026bc8e8
Revises:
Create Date: 2025-03-24 06:08:39.993001+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de20026bc8e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_string', sa.String(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processor_name', sa.String(), nullable=False),
    sa.Column('processor_version', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('expected_reference_count', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'started', 'completed', 'cancelled', name='import_record_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_record_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'started', 'failed', 'completed', 'cancelled', name='import_batch_status'), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_batch')
    op.drop_table('import_record')
    # ### end Alembic commands ###
