"""
Initial import records model.

Revision ID: e3982035daf7
Revises:
Create Date: 2025-02-07 03:03:27.682097+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e3982035daf7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "importrecord",
        sa.Column("search_string", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("searched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("processor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "processor_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_record_count", sa.Integer(), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created", "started", "completed", "cancelled", name="importstatus"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("importrecord")
    # ### end Alembic commands ###
