"""
realign import_batch_status enum

Revision ID: e452ec50ed26
Revises: 13677d5ee575
Create Date: 2025-05-15 04:39:01.501059+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e452ec50ed26'
down_revision: Union[str, None] = '13677d5ee575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'failed' to the import_batch_status enum
    op.execute("ALTER TYPE import_batch_status ADD VALUE IF NOT EXISTS 'failed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing an enum value is not directly supported in PostgreSQL.
    pass
    # ### end Alembic commands ###
