"""
update unique constraint

Revision ID: e55630485612
Revises: a59a0d4dc6dc
Create Date: 2025-04-13 23:08:34.300039+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e55630485612'
down_revision: Union[str, None] = 'a59a0d4dc6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_enhancement', 'enhancement', type_='unique')
    op.create_unique_constraint('uix_enhancement', 'enhancement', ['enhancement_type', 'reference_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_enhancement', 'enhancement', type_='unique')
    op.create_unique_constraint('uix_enhancement', 'enhancement', ['enhancement_type', 'reference_id', 'source', 'content'])
    # ### end Alembic commands ###
