"""
remove base_url and collision_strategy

Revision ID: e8133082064b
Revises: 948cfaa5bb9e
Create Date: 2025-10-17 04:28:45.944629+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8133082064b'
down_revision: Union[str, None] = '948cfaa5bb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batch', 'collision_strategy')
    op.drop_column('robot', 'base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('import_batch', sa.Column('collision_strategy', postgresql.ENUM('discard', 'fail', 'overwrite', 'merge_aggressive', 'merge_defensive', 'deprecated', 'append', name='collision_strategy'), server_default=sa.text("'deprecated'::collision_strategy"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
