"""
Add index to PendingEnhancement

Revision ID: f80394742e3e
Revises: 5f5b2e791c6e
Create Date: 2025-08-29 05:37:11.086987+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f80394742e3e'
down_revision: Union[str, None] = '5f5b2e791c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pending_enhancement_robot_id_status', 'pending_enhancement', ['robot_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_enhancement_robot_id_status', table_name='pending_enhancement')
    # ### end Alembic commands ###
