"""
add indexes to reference and import foreign keys

Revision ID: f8ad6d4b122a
Revises: 64242843905a
Create Date: 2025-06-19 08:54:57.805801+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f8ad6d4b122a'
down_revision: Union[str, None] = '64242843905a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enhancement_reference_id', 'enhancement', ['reference_id'], unique=False)
    op.create_index('ix_external_identifier_reference_id', 'external_identifier', ['reference_id'], unique=False)
    op.create_index('ix_import_batch_import_record_id', 'import_batch', ['import_record_id'], unique=False)
    op.create_index('ix_import_result_import_batch_id', 'import_result', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_result_import_batch_id', table_name='import_result')
    op.drop_index('ix_import_batch_import_record_id', table_name='import_batch')
    op.drop_index('ix_external_identifier_reference_id', table_name='external_identifier')
    op.drop_index('ix_enhancement_reference_id', table_name='enhancement')
    # ### end Alembic commands ###
