FROM python:3.12-slim-bookworm AS base
WORKDIR /src

RUN apt-get update && apt-get install -y libpq-dev gcc

RUN pip install poetry poetry-plugin-bundle
COPY pyproject.toml poetry.lock README.md ./
COPY libs/sdk ./libs/sdk
RUN poetry bundle venv --without docs /src/.venv

COPY tests/e2e /e2e
