services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: destiny_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  fs:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: localuser
      MINIO_ROOT_PASSWORD: localpass
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fs_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 5

  fs-seeder:
    image: minio/mc
    depends_on:
      fs:
        condition: service_healthy
    volumes:
      - ./.minio:/.minio
    working_dir: /.minio
    entrypoint: ["bash", "seed_fileserver.sh"]

volumes:
  db_data:
  fs_data:
