# Greatly simplified Dockerfile for end-to-end tests
# Does not do the recommended multi-stage build that the primary Dockerfile
# does as building via the Docker python SDK does not support buildkit,
# which means we cannot mount the cache.

FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY libs/sdk ./libs/sdk
COPY app/ ./app

RUN uv sync --locked
