FROM destiny-repo
WORKDIR /src

RUN pip install poetry poetry-plugin-bundle
COPY pyproject.toml poetry.lock README.md ./
RUN poetry bundle venv --with=dev /venv

COPY tests/ ./tests

CMD ["pytest", "tests/"]
