services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: destiny_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    profiles:
      - optional
    build:
      context: .
      args:
        POETRY_INSTALL_DEV: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    entrypoint: fastapi dev app/main.py --host 0.0.0.0 --port 8000

  celery:
    profiles:
      - optional
    build:
      context: .
      args:
        POETRY_INSTALL_DEV: "true"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    entrypoint: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app.tasks worker --loglevel=INFO

volumes:
  db_data:
