FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY pyproject.toml uv.lock README.md ./
COPY libs/sdk ./libs/sdk
COPY app/ ./app
COPY uv.lock pyproject.toml ./

# Doesn't use mounts to allow python to build the image (docker-py doesn't support buildkit)
RUN uv sync --locked --dev
