#!/bin/sh
cat > /app/public/runtime-config.json <<EOF
{
  "NEXT_PUBLIC_AZURE_CLIENT_ID":"${NEXT_PUBLIC_AZURE_CLIENT_ID}",
  "NEXT_PUBLIC_AZURE_APPLICATION_ID":"${NEXT_PUBLIC_AZURE_APPLICATION_ID}",
  "NEXT_PUBLIC_API_URL":"${NEXT_PUBLIC_API_URL}",
  "NEXT_PUBLIC_AZURE_LOGIN_URL":"${NEXT_PUBLIC_AZURE_LOGIN_URL}",
  "ENV":"${ENV}"
}
EOF
exec "$@"
