name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.rst"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load .env.example into environment
        # This isn't actually used in the testing but helps in the setup
        run: |
          cp .env.example .env
          mkdir -p .certs
          echo 'dummy certificate for CI only' > .certs/ca.crt

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.14"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --group test

      - name: Run test with pytest via uv
        run: DOCKER_HOSTNAME=172.17.0.1 uv run pytest tests/e2e --build
