name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.rst"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_URL=overwritten-in-docker-compose-e2e
          AZURE_APPLICATION_ID=00000000-0000-0000-0000-000000000000
          AZURE_LOGIN_URL=https://login.microsoftonline.com
          AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
          ENV=dev
          CLI_CLIENT_ID=00000000-0000-0000-0000-000000000000
          MESSAGE_BROKER_URL=overwritten-in-docker-compose-e2e
          MESSAGE_BROKER_NAMESPACE=destiny-repository-staging.servicebus.windows.net
          MESSAGE_BROKER_QUEUE_NAME=taskiq
          EOF

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Remove database volume
        run: |
          # Had a weird issue with the DB persisting data between runs, sporadically
          docker volume rm destiny-repository_db_data || true

      - name: Set up Docker Compose and stream logs
        run: |
          docker compose -f docker-compose.yml -f docker-compose.e2e.yml up -d
          docker compose -f docker-compose.yml -f docker-compose.e2e.yml logs -f &

      - name: Wait for e2e container to finish
        run: |
          while [ "$(docker inspect -f '{{.State.Status}}' e2e 2>/dev/null)" != "exited" ]; do
            sleep 5
          done

      - name: Check e2e container exit code
        run: |
          EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' e2e)
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "E2E tests failed with exit code $EXIT_CODE"
            exit 1
          fi
          echo "E2E tests passed"

      - name: Clean up Docker Compose
        if: always()
        run: docker compose down -v
