name: Release SDK to PyPI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      branch:
        description: "Branch to deploy from"
        required: true
        default: "main"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Placeholder step
        run: echo "This is a stub - no actual release functionality yet"
